### ISSUE TITLE
Shows spinner in the fzf instance as if it's loading

### ISSUE THREAD

**Issue by ghost** [danielronalds/fzf-wrapped#1]
The fzf instance shows the spinner as if it's searching for something, I think it's because the stdin isn't closed

Example:
![before](https://github.com/user-attachments/assets/42650f0f-2f2d-4931-a8d6-3151611efb0d)

It seems to be fixed by dropping stdin in the `output()` method

After:
![after](https://github.com/user-attachments/assets/e4bc2f1a-d662-4870-9c45-d06b874bb222)

Code Before:

``` rs
    pub fn output(self) -> Option<String> {
        let output = self.instance?.wait_with_output().ok()?;
        Some(String::from_utf8_lossy(&output.stdout).trim().to_string())
    }
```

Code After:

``` rs
    pub fn output(self) -> Option<String> {
    	drop(self.stdin);
        let output = self.instance?.wait_with_output().ok()?;
        Some(String::from_utf8_lossy(&output.stdout).trim().to_string())
    }
```

**Comment by danielronalds** [comment]
Hi, thanks for your issue and for providing the fix! I'll make the change and release it

**Comment by danielronalds** [comment]
Just released this to crates.io, updating your `Cargo.toml` to `"0.1.4"` will fix this issue
